### ISSUE TITLE
Parsing, Generate Simple Report

### ISSUE THREAD

**Issue by arky** [bassosimone/test-lists-gardener#1]
Currently Gardener stores the test results in a JSON file. 

It would great if the results could output into a simple text file (or standard out) with few items such as 'Source file, URI, Problem Type'

**Comment by bassosimone** [comment]
I did this in https://github.com/ooni/probe-cli/pull/1114. The `gardener dnsreport` tool generates a CSV report.

**Comment by arky** [comment]
Thanks @bassosimone
